spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erp
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: erp
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 3000
liquibase:
  change-log: classpath:liquibase/master.xml
  enabled: true
  drop-first: false
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mxp.erp.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
server:
  port: 8080
  context-path: /erp
logging:
  level:
    com.mxp.erp.dao: debug
